name = "connect-4"
main = "cloudflare-worker/index.js"
compatibility_date = "2026-04-25"
workers_dev = true

account_id = "f2056d84cc95eda0bb73f79261962b87"

[[kv_namespaces]]
binding = "CONNECT4_ROOMS"
id = "c2e1b9f2-6377-40de-9dac-438cd14e45cb"
